version: "3"
services:
  http-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    logging:
      options:
        max-size: "5m"
        max-file: "2"
  wdio:
    build: .
    image: wdio

  jenkins:
    build: jenkins
    environment:
      - VIRTUAL_HOST=jenkins.localhost
      - VIRTUAL_PORT=8080
    volumes:
      - '~/docker-data/jenkins/home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - http-proxy
    restart: always
    logging:
      options:
        max-size: "5m"
        max-file: "2"
